const { ROLES, ALL_ROLES } = require('./roles');
const {
  STUDENT_STATUS,
  ACTIVITY_STATUS,
  MONTH_STATUS,
  PAYMENT_STATUS,
  PAYMENT_MODE,
  MONTH_NAMES,
  MONTH_SHORT,
  AUDIT_ACTION,
  AUDIT_RESOURCE_TYPE,
} = require('./status');

module.exports = {
  ROLES,
  ALL_ROLES,
  STUDENT_STATUS,
  ACTIVITY_STATUS,
  MONTH_STATUS,
  PAYMENT_STATUS,
  PAYMENT_MODE,
  MONTH_NAMES,
  MONTH_SHORT,
  AUDIT_ACTION,
  AUDIT_RESOURCE_TYPE,
};
